#!name=Locket Gold V10 (Duy Mod)
#!desc=Mở khóa Locket Gold: Upload 4K, Video dài, Custom Icon. Server riêng của PhanDucDuy.
#!author=PhanDucDuy
#!homepage=https://github.com/phanducduy6
#!icon=https://raw.githubusercontent.com/phanducduy6/locket-gold-by-duychute/main/icon.png
#!select=select

[General]
# Cấu hình chung để tối ưu
bypass-system = true
loglevel = notify

[Rule]
# Không cần rule chặn đặc biệt cho bản này

[Script]
# Đây là dòng quan trọng nhất, nó trỏ về file JS trong kho của bạn
Locket_Gold_V10 = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/v1\/(subscribers|receipts), requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/phanducduy6/locket-gold-by-duychute/main/LocketGold.js

[MitM]
# Kích hoạt giải mã HTTPS cho server thanh toán
hostname = api.revenuecat.com
