#!name=Locket Gold V10 (Duy Mod)
#!desc=Mở khóa Locket Gold: Upload 4K, Video dài, Custom Icon. Server riêng của PhanDucDuy.
#!author=PhanDucDuy
#!homepage=https://github.com/phanducduy6
#!icon=https://raw.githubusercontent.com/phanducduy6/locket-gold-by-duychute/main/icon.png
#!select=select
#!desc=Mở khoá premium cho ứng dụng Locket Widget 
# 💬 facebook: https://www.facebook.com/phan.duc.duy.6
# 🚀 Released by: duychute  
#!version= 8

[General]
user-agent = Locket/1.0.0 (iPhone; iOS 26; Scale/3.00)

[Script]

# ~ Enhanced for Shadowrocket, Surge, & LanceX
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/refs/heads/main/locketfix1.js, requires-body=true, max-size=-1, timeout=120
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.*\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/NightmarketServer/Locket/refs/heads/main/header.js, timeout=120

[MITM]
hostname = api.revenuecat.com, raw.githubusercontent.com
# 👤 Author: Phan Đức Duy
